[project]
name = "text-generation-webui-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "accelerate==1.8.*",
    "colorama>=0.4.6",
    "datasets>=4.0.0",
    "einops>=0.8.1",
    "fastapi==0.112.4",
    "flask-cloudflared==0.0.14",
    "gradio==4.37.*",
    "html2text==2025.4.15",
    "jinja2==3.1.6",
    "markdown>=3.8.2",
    "numpy==2.2.*",
    "pandas>=2.3.1",
    "peft==0.17.*",
    "pillow>=9.5.0",
    "psutil>=7.0.0",
    "pydantic==2.8.2",
    "pypdf2==3.0.1",
    "python-docx==1.1.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "safetensors==0.6.*",
    "scipy>=1.16.0",
    "sentencepiece>=0.2.0",
    "sse-starlette==1.6.5",
    "tensorboard>=2.19.0",
    "tiktoken>=0.9.0",
    "tqdm>=4.67.1",
    "transformers==4.56.*",
    "triton-windows==3.3.1.post19 ; platform_system == 'Windows'",
    "wandb>=0.21.0",
]

[project.optional-dependencies]
amd = [
    "exllamav2",
    "llama_cpp_binaries==0.37.0+vulkan",
    "pytorch_triton_rocm",
    "torch==2.7.0",
]
amd-noavx2 = [
    "exllamav2",
    "llama_cpp_binaries==0.37.0+vulkanavx",
    "pytorch_triton_rocm",
    "torch==2.7.0",
]
cpuonly = ["exllamav2", "llama_cpp_binaries==0.37.0+cpuavx2", "torch==2.7.0"]
cpuonly-noavx2 = [
    "exllamav2",
    "llama_cpp_binaries==0.37.0+cpuavx",
    "torch==2.7.0",
]
cuda = [
    "bitsandbytes==0.46.*",
    "exllamav2",
    "exllamav3",
    "flash_attn",
    "llama_cpp_binaries==0.37.0+cu128",
    "torch==2.7.0",
]
cuda-noavx2 = [
    "bitsandbytes==0.46.*",
    "exllamav2",
    "exllamav3",
    "flash_attn",
    "llama_cpp_binaries==0.37.0+cu128avx",
    "torch==2.7.0",
]

[tool.uv]
conflicts = [
    [
        { extra = "amd" },
        { extra = "amd-noavx2" },
        { extra = "cpuonly" },
        { extra = "cpuonly-noavx2" },
        { extra = "cuda" },
        { extra = "cuda-noavx2" },
    ],
]

environments = [
    "platform_system == 'Linux' and platform_machine == 'x86_64'",
    "platform_system == 'Windows' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch = [
    { extra = "amd", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', index = "torch-linux-rocm" },
    { extra = "amd-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', index = "torch-linux-rocm" },
    { extra = "cpuonly", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', index = "torch-linux-cpuonly" },
    { extra = "cpuonly-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', index = "torch-linux-cpuonly" },
    { extra = "cuda", index = "torch-cuda" },
    { extra = "cuda-noavx2", index = "torch-cuda" },
]
pytorch_triton_rocm = [
    { extra = "amd", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', index = "torch-linux-rocm" },
    { extra = "amd-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', index = "torch-linux-rocm" },
]

llama_cpp_binaries = [
    { extra = "amd", marker = 'platform_system == "Linux" and platform_machine == "x86_64"', url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+vulkan-py3-none-linux_x86_64.whl" },
    { extra = "amd", marker = 'platform_system == "Windows"', url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+vulkan-py3-none-win_amd64.whl" },
    { extra = "amd-noavx2", marker = "platform_system == 'Linux' and platform_machine == 'x86_64'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+vulkanavx-py3-none-win_amd64.whl" },
    { extra = "amd-noavx2", marker = "platform_system == 'Windows'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+vulkanavx-py3-none-linux_x86_64.whl" },
    { extra = "cpuonly", marker = "platform_system == 'Linux' and platform_machine == 'x86_64' and python_version == '3.11'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cpuavx2-py3-none-linux_x86_64.whl" },
    { extra = "cpuonly", marker = "platform_system == 'Windows' and python_version == '3.11'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cpuavx2-py3-none-win_amd64.whl" },
    { extra = "cpuonly-noavx2", marker = "platform_system == 'Linux' and platform_machine == 'x86_64' and python_version == '3.11'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cpuavx-py3-none-linux_x86_64.whl" },
    { extra = "cpuonly-noavx2", marker = "platform_system == 'Windows' and python_version == '3.11'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cpuavx-py3-none-win_amd64.whl" },
    { extra = "cuda", marker = "platform_system == 'Windows' and python_version == '3.11'", url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cu124-py3-none-win_amd64.whl" },
    { extra = "cuda", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cu124-py3-none-linux_x86_64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cu124avx-py3-none-linux_x86_64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/oobabooga/llama-cpp-binaries/releases/download/v0.46.0/llama_cpp_binaries-0.46.0+cu124avx-py3-none-win_amd64.whl" },
]

exllamav2 = [
    { extra = "amd", marker = "platform_system != 'Darwin' and platform_machine != 'x86_64'", url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2-py3-none-any.whl" },
    { extra = "amd", marker = "platform_system == 'Linux' and platform_machine == 'x86_64' and python_version == '3.11'", url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2+rocm6.2.4.torch2.6.0-cp311-cp311-linux_x86_64.whl" },
    { extra = "amd-noavx2", marker = "platform_system != 'Darwin' and platform_machine != 'x86_64'", url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2-py3-none-any.whl" },
    { extra = "amd-noavx2", marker = "platform_system == 'Linux' and platform_machine == 'x86_64' and python_version == '3.11'", url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2+rocm6.2.4.torch2.6.0-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda", marker = 'platform_system == "Linux" and platform_machine != "x86_64"', url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2-py3-none-any.whl" },
    { extra = "cuda", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2+cu128.torch2.7.0-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2+cu128.torch2.7.0-cp311-cp311-win_amd64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Linux" and platform_machine != "x86_64"', url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2-py3-none-any.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2+cu128.torch2.7.0-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav2/releases/download/v0.3.2/exllamav2-0.3.2+cu128.torch2.7.0-cp311-cp311-win_amd64.whl" },
]

exllamav3 = [
    { extra = "cuda", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav3/releases/download/v0.0.6/exllamav3-0.0.6+cu128.torch2.7.0-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav3/releases/download/v0.0.6/exllamav3-0.0.6+cu128.torch2.7.0-cp311-cp311-win_amd64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav3/releases/download/v0.0.6/exllamav3-0.0.6+cu128.torch2.7.0-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/turboderp-org/exllamav3/releases/download/v0.0.6/exllamav3-0.0.6+cu128.torch2.7.0-cp311-cp311-win_amd64.whl" },
]

flash_attn = [
    { extra = "cuda", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/kingbri1/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu128torch2.7.0cxx11abiFALSE-cp311-cp311-win_amd64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"', url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl" },
    { extra = "cuda-noavx2", marker = 'platform_system == "Windows" and python_version == "3.11"', url = "https://github.com/kingbri1/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu128torch2.7.0cxx11abiFALSE-cp311-cp311-win_amd64.whl" },
]

[[tool.uv.index]]
name = "torch-linux-rocm"
url = "https://download.pytorch.org/whl/rocm6.3"
explicit = true

[[tool.uv.index]]
name = "torch-linux-cpuonly"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "torch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
